### ISSUE TITLE
ArgumentOutOfRangeException, Cannot extract texture

### ISSUE THREAD

**Issue by SnowyYANG** [darkxex/Rune-Factory-4-Special-Texture-Extractor#1]
I tried the latest release with many texture files, always get a ArgumentOutOfRangeException.

```
RF4STextExtractor.exe bundleMain\I_WeaponA00.texture
```

Type: RES
Code: 0
Initial Offset: 4638

未经处理的异常:  System.ArgumentOutOfRangeException: 要求非负数。
参数名: count
   在 System.IO.BinaryReader.ReadBytes(Int32 count)
   在 RF4STextExtractor.Program.Main(String[] args)

**Comment by darkxex** [comment]
![image](https://user-images.githubusercontent.com/17991404/152200230-c9a526b0-3e19-492f-bbb7-54fccd74f0a4.png)
the app is working, please test with this.
https://github.com/darkxex/Rune-Factory-4-Special-Texture-Extractor/releases/download/1.2/RF4STextureExtractor.exe
i don't know why your app is called RF4STextExtractor.... (?)
if this app not work, try changing the lenguage of OS.

**Comment by SnowyYANG** [comment]
you are right, it works. I type the wrong exe name. sorry.
